
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/layout/AppSidebar";
import AppNavbar from "@/components/layout/AppNavbar";
import { AuthGuard } from "@/components/auth/auth-guard";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
                <AuthGuard>
                    <SidebarProvider>
                        <div className="flex min-h-screen w-full">
                            <AppSidebar />
                            <div className="flex flex-col flex-1">
                                <AppNavbar />
                                <main className="flex-1 p-6">
                                    {children}
                                </main>
                            </div>
                        </div>
                        <Toaster />
                    </SidebarProvider>
                </AuthGuard>
    );
}
